// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Patient_Access_Experian_Project_API.Data;

#nullable disable

namespace Patient_Access_Experian_Project_API.Migrations
{
    [DbContext(typeof(PatientAccessDbContext))]
    [Migration("20260317213814_AddClaimsAndPayers")]
    partial class AddClaimsAndPayers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ClinicId", "StartUtc");

                    b.HasIndex("ProviderId", "StartUtc");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.AvailabilityWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("EndMinuteOfDay")
                        .HasColumnType("int");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StartMinuteOfDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "DayOfWeek", "StartMinuteOfDay", "EndMinuteOfDay")
                        .IsUnique();

                    b.ToTable("AvailabilityWindows");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            DayOfWeek = 1,
                            EndMinuteOfDay = 1020,
                            ProviderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            StartMinuteOfDay = 540
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            DayOfWeek = 2,
                            EndMinuteOfDay = 1020,
                            ProviderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            StartMinuteOfDay = 540
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            DayOfWeek = 3,
                            EndMinuteOfDay = 1020,
                            ProviderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            StartMinuteOfDay = 540
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            DayOfWeek = 4,
                            EndMinuteOfDay = 1020,
                            ProviderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            StartMinuteOfDay = 540
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            DayOfWeek = 5,
                            EndMinuteOfDay = 1020,
                            ProviderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            StartMinuteOfDay = 540
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            DayOfWeek = 1,
                            EndMinuteOfDay = 1020,
                            ProviderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            StartMinuteOfDay = 540
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            DayOfWeek = 3,
                            EndMinuteOfDay = 1020,
                            ProviderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            StartMinuteOfDay = 540
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            DayOfWeek = 5,
                            EndMinuteOfDay = 1020,
                            ProviderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            StartMinuteOfDay = 540
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc1"),
                            DayOfWeek = 2,
                            EndMinuteOfDay = 1020,
                            ProviderId = new Guid("44444444-4444-4444-4444-444444444444"),
                            StartMinuteOfDay = 540
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc2"),
                            DayOfWeek = 4,
                            EndMinuteOfDay = 1020,
                            ProviderId = new Guid("44444444-4444-4444-4444-444444444444"),
                            StartMinuteOfDay = 540
                        });
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AllowedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DenialReasonCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PatientResponsibility")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PayerPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubmissionIdempotencyKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("SubmissionIdempotencyKey");

                    b.HasIndex("PayerId", "CreatedUtc");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.ClaimServiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ChargeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimServiceLines");
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.ClaimTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId", "CreatedUtc");

                    b.ToTable("ClaimTransactions");
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Health Clinic A",
                            TimeZone = "America/Chicago"
                        });
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.CoverageCheckLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Copay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CoverageStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DeductibleRemaining")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Eligible")
                        .HasColumnType("bit");

                    b.Property<decimal>("EstimatedPatientResponsibility")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("PatientId", "CreatedUtc");

                    b.ToTable("CoverageCheckLogs");
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Email = "alex.johnson@gmail.com",
                            FirstName = "Alex",
                            LastName = "Johnson",
                            Phone = "555-111-2222"
                        });
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.Payer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Payers");
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Dr. Maya Patel",
                            Specialty = "Primary Care"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Dr. Jordan Lee",
                            Specialty = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Dr. Sofia Ramirez",
                            Specialty = "Dermatology"
                        });
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.Appointment", b =>
                {
                    b.HasOne("Patient_Access_Experian_Project_API.Models.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Patient_Access_Experian_Project_API.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Patient_Access_Experian_Project_API.Models.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Patient");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.AvailabilityWindow", b =>
                {
                    b.HasOne("Patient_Access_Experian_Project_API.Models.Provider", "Provider")
                        .WithMany("AvailabilityWindows")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.Claim", b =>
                {
                    b.HasOne("Patient_Access_Experian_Project_API.Models.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patient_Access_Experian_Project_API.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patient_Access_Experian_Project_API.Models.Payer", "Payer")
                        .WithMany("Claims")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patient_Access_Experian_Project_API.Models.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Patient");

                    b.Navigation("Payer");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.ClaimServiceLine", b =>
                {
                    b.HasOne("Patient_Access_Experian_Project_API.Models.Claim", "Claim")
                        .WithMany("ServiceLines")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.ClaimTransaction", b =>
                {
                    b.HasOne("Patient_Access_Experian_Project_API.Models.Claim", "Claim")
                        .WithMany("Transactions")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.Claim", b =>
                {
                    b.Navigation("ServiceLines");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.Payer", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("Patient_Access_Experian_Project_API.Models.Provider", b =>
                {
                    b.Navigation("AvailabilityWindows");
                });
#pragma warning restore 612, 618
        }
    }
}
